### ISSUE TITLE
Tests for packages are failing after beta release

### ISSUE THREAD

**Issue by gurkanindibay** [citusdata/tools#220]

**Comment by hanefi** [comment]
Here is the failure during the following job step:

https://github.com/citusdata/tools/blob/1e5c04609f840af1fa108ee6e47ac5f449362ef6/.github/workflows/package-tests.yml#L34-L44

The failure output:

```
Run export PROJECT_VERSION="11.0.0_beta"
  export PROJECT_VERSION="11.0.0_beta"
  echo "project_version: 11.0.0_beta"
  # To be able to test pipeline without triggering with project_version parameter using workflow_dispatch parameter,
  # if workflow_dispatch parameter is empty, 10.[2](https://github.com/citusdata/tools/runs/5677881913?check_suite_focus=true#step:6:2).1 parameter is set to execute pipeline.
  [ -z ${PROJECT_VERSION} ] && export PROJECT_VERSION=10.2.1
  POSTGRES_VERSIONS=$(python -m packaging_automation.get_postgres_versions --project_version ${PROJECT_VERSION})
  echo "Postgres Version: ${POSTGRES_VERSIONS}"
  echo "::set-output name=pg_versions::${POSTGRES_VERSIONS}"
  shell: /usr/bin/bash -e {0}
project_version: 11.0.0_beta
Traceback (most recent call last):
  File "/usr/lib/python[3](https://github.com/citusdata/tools/runs/5677881913?check_suite_focus=true#step:6:3).8/runpy.py", line 19[4](https://github.com/citusdata/tools/runs/5677881913?check_suite_focus=true#step:6:4), in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/runner/work/tools/tools/packaging_automation/get_postgres_versions.py", line 11, in <module>
    postgres_versions = get_postgres_versions_from_matrix_file(args.project_version)
  File "/home/runner/work/tools/tools/packaging_automation/test_citus_package.py", line [5](https://github.com/citusdata/tools/runs/5677881913?check_suite_focus=true#step:6:5)2, in get_postgres_versions_from_matrix_file
    pg_versions = get_supported_postgres_release_versions(POSTGRES_MATRIX_FILE, project_version)
  File "/home/runner/work/tools/tools/packaging_automation/common_tool_methods.py", line [6](https://github.com/citusdata/tools/runs/5677881913?check_suite_focus=true#step:6:6)13, in get_supported_postgres_release_versions
    release_versions = match_release_version(versions_dictionary, package_version)
  File "/home/runner/work/tools/tools/packaging_automation/common_tool_methods.py", line 634, in match_release_version
    package_version_numeric = get_numeric_counterpart_of_version(package_version)
  File "/home/runner/work/tools/tools/packaging_automation/common_tool_methods.py", line 662, in get_numeric_counterpart_of_version
    numeric_counterpart = numeric_counterpart + int(num) * multiplier
ValueError: invalid literal for int() with base [10](https://github.com/citusdata/tools/runs/5677881913?check_suite_focus=true#step:6:10): '0_beta'
Error: Process completed with exit code 1.
```

@gurkanindibay please include information such as the ones above when opening an issue. Make it easier for the readers to understand what is actually going on.

**Comment by hanefi** [comment]
Apparently `get_postgres_versions` expects the patch version to be an integer, and not something like `0_beta`

**Comment by onurctirtir** [comment]
not applicable anymore as we're not doing beta releases since 11.x
